language: node_js
dist: trusty
node_js: 
- 8.0.0
branches:
  only:
  - master
addons:
  postgresql: '9.5'
env:
  global:
  - NODE_ENV=test
before_script:
- psql -c 'create database "bookmarks-db-test";' -U postgres
script:
- npm run lint
- npm run cover
